### ISSUE TITLE
Getting "'StanModel' object has no attribute 'fit_class' error while using prophet model

### ISSUE THREAD

**Issue by bhatiaaman** [WillKoehrsen/Data-Analysis#10]
I am trying to use prophet mode on TechM stock 
model , model_data = techM.create_prophet_model()

I am getting error 
"
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-0bdace2234ef> in <module>()
----> 1 model , model_data = techM.create_prophet_model()

~/AmanCode/Python/Stocker/stocker.py in create_prophet_model(self, days, resample)
    447             stock_history = self.resample(stock_history)
    448 
--> 449         model.fit(stock_history)
    450 
    451         # Make and predict for next year with future dataframe

~/anaconda3/lib/python3.6/site-packages/fbprophet/forecaster.py in fit(self, df, **kwargs)
    834             try:
    835                 params = model.optimizing(
--> 836                     dat, init=stan_init, iter=1e4, **kwargs)
    837             except RuntimeError:
    838                 params = model.optimizing(

~/anaconda3/lib/python3.6/site-packages/pystan/model.py in optimizing(self, data, seed, init, sample_file, algorithm, verbose, as_vector, **kwargs)
    470             data = {}
    471         seed = pystan.misc._check_seed(seed)
--> 472         fit = self.fit_class(data, seed)
    473 
    474         m_pars = fit._get_param_names()

AttributeError: 'StanModel' object has no attribute 'fit_class'"

I tried updating numpy as well as pystan , but still getting the same error ..

**Comment by WillKoehrsen** [comment]
That is a problem with either Prophet, numpy, or pystan.  Did you try reinstalling with conda? 

[This thread](https://github.com/facebook/prophet/issues/249) might be helpful.

**Comment by bhatiaaman** [comment]
Thanks..

I uninstalled prophet and pystan and then reinstalled using pip with
no-cache. It is working fine now

**Comment by WillKoehrsen** [comment]
Good to hear. Prophet is relatively new and there are still issues with installation.
