### ISSUE TITLE
Not able to run stocker

### ISSUE THREAD

**Issue by manav157** [WillKoehrsen/Data-Analysis#11]
Hi i have already installed all the packages required but i am not able to run this code on jupyter.
![image](https://user-images.githubusercontent.com/37308518/37567318-589850a0-2aeb-11e8-96f7-fde5e5d56cb0.png)
please help me where i am lagging behind.
It would be very helpful.

**Comment by manisaivecha341** [comment]
rather than a jupyter notebook try to run a interactive python program of stocker on your command interface .. it worked with mine.

**Comment by elessarrr** [comment]
@manisaivecha341  could you elaborate? What do you mean by interactive python program? Thanks

**Comment by manisaivecha341** [comment]
See @elessarrr can u mention your specifications of your system and python idle

**Comment by willm78** [comment]
@manav157 Not sure if this is your issue or not, but you forgot to capitalize a word. 

Where you have:
`from stocker import stocker`
should be:
`from stocker import Stocker`

**Comment by mdoliner** [comment]
+1 to @BoomPakorn seems like there's an issue at all places where pandas boolean date filtering is being used

**Comment by BoomPakorn** [comment]
I found the way to fix it. just remove .date() after start_date & end_date in stocker

![screenshot 2018-05-23 09 29 14](https://user-images.githubusercontent.com/28772384/40400333-dc95c8ca-5e6b-11e8-9599-1bef41b11336.png)

**Comment by WillKoehrsen** [comment]
Could this be an issue with the newest version of Pandas (version 0.23)? It looks like there were changes made to the datetime module [Pandas 0.23 changes](https://pandas.pydata.org/pandas-docs/stable/whatsnew.html).

**Comment by fallen293** [comment]
@WillKoehrsen That is definitely the issue. 
I used `pip install pandas==0.22.0` and that fixed my issues
Good catch!

**Comment by WillKoehrsen** [comment]
That's good to hear. I will update Stocker to reflect the newest version of Pandas when I get the chance.

**Comment by long4glasgow** [comment]
I have encountered the same issue of date error as the @mdoliner, pandas == 0.22.0,  not sure what is causing this error.

**Comment by WillKoehrsen** [comment]
I'm going to close this because the original issue has been resolved. There still appear to be some errors with `datetimes`, but I think that is a matter of using the correct version of `pandas`.

**Comment by rajeev-nanhu** [comment]
ImportError: cannot import name 'StringIO' from 'pandas.compat' (C:\Users\RAJEEV CHOUDHARY\anaconda3\lib\site-packages\pandas\compat\__init__.py)


This messgae is displaying after installation of stocker.
