### ISSUE TITLE
Package Installation 2018

### ISSUE THREAD

**Issue by shwin12345** [WillKoehrsen/Data-Analysis#13]
I just had a question about how you installed your packages... I am having issues installing pystan because it requires a C++ compiler, however, I am not able to install one. This then affects the installation of fbprophet. If you could explain what you did, that would be of great help.

Thanks!

**Comment by VK9999** [comment]
Hello Shwin,

Try to install visual studio 2015 IDE and it should resolve that issue.

**Comment by VictorHM** [comment]
This helped me to install the compiler and get it set up

https://pystan.readthedocs.io/en/latest/windows.html

The key part is this ``conda install libpython m2w64-toolchain -c msys2``

**Comment by WillKoehrsen** [comment]
You can use `conda` to install a C++ compiler as recommended by @VictorHM.

I use [mingw installed with Anaconda](https://anaconda.org/anaconda/mingw) (I'm on Windows which might affect the compiler required). `conda install mingw` should work.
