### ISSUE TITLE
Quandl API Key not working

### ISSUE THREAD

**Issue by shwin12345** [WillKoehrsen/Data-Analysis#15]
Error Retrieving Data....
(Status 400) (Quandl Error QEAx01) We could not recognize your API key. Please check your API key and try again.

error was given even after Quandl account was made, key was given, and a new key was given.

**Comment by WillKoehrsen** [comment]
That's not going to be an issue with `Stocker`. I'd say try to generate a new key and make sure you have copied and pasted it correctly. If issues persist, then get in contact with [Quandl](https://www.quandl.com/docs-and-help).
