### ISSUE TITLE
stocker not found

### ISSUE THREAD

**Issue by mishra48** [WillKoehrsen/Data-Analysis#18]
when i try to use your code in pycharm it says that no module named stocker found.

**Comment by QSCTech-Sange** [comment]
It appears that u haven't installed all the necessary modules.

**Comment by leodavinci111** [comment]
Same issue her.e. I did verify that all the packages in the readme file are satisfied.

**Comment by trupti-jadhav** [comment]
Facing the same issue - no module named stocker

**Comment by leodavinci111** [comment]
You have to copy the file in your folder

**Comment by WillKoehrsen** [comment]
You need to make sure to import Stocker in the correct directory. Make sure `stocker.py` is in the directory where you are running your scripts or Jupyter Notebook.
