### ISSUE TITLE
Jupyter does not recognize fbprophet

### ISSUE THREAD

**Issue by VictorHM** [WillKoehrsen/Data-Analysis#19]
Hi all, I configured the system and installed the required libraries. Doing so in a virtual environment. So, I activate the environment to have libraries available and then try to run Jupyter opening the notebook I want to work with using this command:

jupyter notebook D:\Projects\stocker\Stocker_test.ipynb

being stocker the folder in which I downloaded Stocker files. However, if fails and does not recognises fbprophet.
![error_fbprophet](https://user-images.githubusercontent.com/2629126/46260007-1d1e2280-c4e1-11e8-9cdb-69bb41a0f54a.jpg)

The message is "ModuleNotFoundError: No module named 'fbprophet'". Any suggestion how to solve this? Other libraries seem to be loading properly. Thanks

**Comment by VictorHM** [comment]
Update:
I didn't have much time to put on this, but I have some extra details and doubts that could help others to understand the problem.

First of all, I can run fbprophet through an interactive session, so it seems to indicate that the libraries are installed. however, it does not load in Jupyter and I saw that Jupyter could be running IPython as the kernel for Python. So that makes think about a few questions I don't have an answer to:
- Could it be the cause? Is it due to a bad configuration on my side? 
- Is it possible to make Jupyter run a different core for python? That could be the cause of the problem.

Thank you very much!

**Comment by QSCTech-Sange** [comment]
I don' think you have installed fbprophet successfully. It really struggles me when installing it.

I solved it by using “conda install -c conda-forge fbprophet” in conda. I'm not sure it will help you, but it works fine on my laptop.

Hope u can solve it soon.

**Comment by WillKoehrsen** [comment]
Check to make sure that you have all the packages correctly installed. `fbprophet` can be difficult to get working, so you might want to look at [the documentation](https://facebook.github.io/prophet/docs/installation.html#python) or search around the web for your error. 

If you can run `fbprophet` in a terminal Python session, then you probably have it installed but I don't know why Jupyter would not be able to find it. Make sure to use the same version of Python in Jupyter as in the terminal!
