### ISSUE TITLE
Incorrect comment and heading in Bayesian Linear Regression Project.ipynb

### ISSUE THREAD

**Issue by divik544** [WillKoehrsen/Data-Analysis#20]
In the mentioned file we are selecting 6 features and further performing predictions using 6 features but the heading and comment says we are selecting 5 features(ref cell no. 22 in the notebook).

**Comment by WillKoehrsen** [comment]
You are correct. This would be a great issue to correct with a pull request!

**Comment by divik544** [comment]
I am interested in correcting this issue. I will open a pull request shortly with the required changes.

**Comment by WillKoehrsen** [comment]
That would be great! Thank you very much.

**Comment by WillKoehrsen** [comment]
Closed by #21
