### ISSUE TITLE
ImportError: No module named quandl

### ISSUE THREAD

**Issue by untamedkk** [WillKoehrsen/Data-Analysis#25]
I am a newbie in Python trying to run as README.md has steps but getting error as per attached screenshot.

<img width="435" alt="screenshot 2018-11-22 at 7 22 49 pm" src="https://user-images.githubusercontent.com/14163891/48899992-192cd200-ee8c-11e8-8f79-ea42145b9578.png">

<img width="781" alt="screenshot 2018-11-22 at 7 32 19 pm" src="https://user-images.githubusercontent.com/14163891/48900451-5e9dcf00-ee8d-11e8-82a7-aadccc18364b.png">

**Comment by WillKoehrsen** [comment]
You are using `pip3` to install `quandl`  which installs the module for Python 3 but the screenshot shows you are trying to import it in Python 2.7. You either need to use Python 3, or use `pip` to install the module for Python 2.
