### ISSUE TITLE
Can't pip install fbprophet

### ISSUE THREAD

**Issue by Joshpk29** [WillKoehrsen/Data-Analysis#26]
I keep running into errors when I try 'pip install fbprophet' specifically it seems that the setup.py keep throwing the error does anyone have any suggestions?

**Comment by WillKoehrsen** [comment]
I'm not sure the cause of your specific issue, but I have heard of trouble installing `fbprophet`. Try looking at [the documentation](https://facebook.github.io/prophet/docs/installation.html#python). You need to install `pystan` first which requires a C++ compiler such as [mingw for Windows](https://mingw-w64.org/).

According to the documentation, `fbprophet` should be installable with both `pip` and `conda`. Try using `conda` if `pip` is failing and make sure to install all the requirements.
