### ISSUE TITLE
Unreachable datasets

### ISSUE THREAD

**Issue by enesMesut** [WillKoehrsen/Data-Analysis#27]
Hi Will, i can't reach the datasets(flights,flights,airlines) which you use for analysis, visualize would you share with proper way because i want to examine your code step by step with my local jupyter notebook.

**Comment by WillKoehrsen** [comment]
Hello,
Which folders/notebooks are you referring to? There are quite a few in this repo (sorry for that) so it's difficult to keep track. If you can point the script or notebook with the data in question, I'll try to locate it!

**Comment by enesMesut** [comment]
Hello Will. im sorry your repository is a treasure. the datasets i mention in Data-Analysis/univariate_dist/data/  path.

**Comment by WillKoehrsen** [comment]
All of the datasets are located in the repo ([link](https://github.com/WillKoehrsen/Data-Analysis/tree/master/univariate_dist/data))!
