### ISSUE TITLE
in plotly-time-series.ipynb Value error when reading the csv

### ISSUE THREAD

**Issue by zinyosrim** [WillKoehrsen/Data-Analysis#30]
`df = pd.read_csv('building_one.csv', header=[0, 1], index_col=False)` produces a
ValueError: index_col must only contain row numbers when specifying a multi-index header.

**Comment by zinyosrim** [comment]
To resolve: Copied the raw data from https://media.githubusercontent.com/media/WillKoehrsen/Data-Analysis/master/plotly/building_one.csv and saved it as building_one.csv

**Comment by WillKoehrsen** [comment]
Yes, the `csv` files are saved in [Git Large File Storage])(https://git-lfs.github.com/). To access them, you have to download the original raw file from GitHub since the file if you pull the repository is only a pointer. Thanks for posting the solution!
