### ISSUE TITLE
'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by Treibs2** [WillKoehrsen/Data-Analysis#69]
Hey, I'm pretty new to all this, so this may be an error on my part... Anyway, I'm running a jupyter notebook and keep getting the following error: 'DataFrame' object has no attribute 'ix'.  Please see the picture attached.  Thanks for your help in advance.
<img width="1092" alt="Screen Shot 2021-02-20 at 5 31 24 PM" src="https://user-images.githubusercontent.com/21163196/108610168-826c5a00-73a1-11eb-8e7a-ceea89c799c2.png">

**Comment by ClarkKen6** [comment]
How did your resolve this?

**Comment by Treibs2** [comment]
Do you still need help with this? Sorry, I missed the notification that someone responded

**Comment by ClarkKen6** [comment]
No thanks @Treibs2, appreciate the reply :)
