### ISSUE TITLE
Data is outdated. (Stocker)

### ISSUE THREAD

**Issue by Pixel8edstudios** [WillKoehrsen/Data-Analysis#70]
Hello, I cannot help but notice that data input stops at a certain point, leading the predictor to predict wildly inaccurate stock prices because the last stock information that it has been given was from about 2 years ago. Are there any ways or plans to move away from quand and to a newer way of data collection? Thank you.

**Comment by jfarrell423** [comment]
Maybe the author can offer instructions to connect to the user's stock exchange. Etrade offers a Python API to connect to a user's personal account. They have instructions for s sandbox and the production connections. I did a demo a few months ago:

https://www.youtube.com/watch?v=WW7gD19ph4U

**Comment by VianneyMI** [comment]
@Pixel8edstudios you can use yahoo finance python library for newer data. It is free to use
