### ISSUE TITLE
Other exchanges

### ISSUE THREAD

**Issue by pvjpavankumar** [WillKoehrsen/Data-Analysis#9]
First of all, your prediction algorithms are very good. 

But the current implementation is looking into only NASDAQ I guess. How can I get the stock predictions for the tickers/symbols (companies) which are in other exchanges like Singapore, China, India, London ?

I tried with those. But they are not working.

**Comment by WillKoehrsen** [comment]
I am using the Quandl Wiki database which has over 3000 stocks.  You can view the complete list under data/stock_list.csv. 

I am definitely open to including other stock exchanges. If you can find them on [Quandl](https://www.quandl.com/search) I can put them in Stocker!

**Comment by WillKoehrsen** [comment]
Do you have any specific tickers in mind?

**Comment by pvjpavankumar** [comment]
Hi Will,

TECHM, INFY etc which are based out of India (NSE and BSE).

Regards

Pavan

**Comment by WillKoehrsen** [comment]
It looks like the National Stock Exchange of India (NSE) and Bombay Stock Exchange (BSE) are available on Quandl! The data looks like it will work, and I will try to integrate these.

**Comment by WillKoehrsen** [comment]
Stocker now supports both the NSE and BSE. 
When you want to use a different exchange, pass it as a keyword argument when instantiating the class.

`techm = Stocker(ticker='TECHM', exchange='NSE')`

**Comment by pvjpavankumar** [comment]
Great. Thanks a lot for the quick turnaround Will.

You saved my day :)

Regards
Pavan

**Comment by garagnoth** [comment]
Would it be possible to include IDX? Tried using pandas_datareader instead of Quandl but failed.

Did that by adding parameter to the __init__ function where user can select whether to use quandl or pandas_datareader:
try:
     if ABC == 'quandl':
            stock = quandl.get('%s/%s' % (exchange, ticker))
     elif ABC == 'pdr':
            stock =...

**Comment by pvjpavankumar** [comment]
Hi,

Thanks. I will test this.

Regards
Pavan
